### ISSUE TITLE
Error when running "php spark ci4adminrbac:install"

### ISSUE THREAD

**Issue by bi2b** [skuadron45/ci4adminlte#1]
I got this error message.

Trying install module
Copying assest to public directory
An uncaught Exception was encountered

Type:        ErrorException
Message:     copy(): Filename cannot be empty
Filename:    D://htdocs/ci4adminlte/vendor/skuadron45/ci4adminrbac/src/Commands/Install.php
Line Number: 54

**Comment by skuadron45** [comment]
please run 
composer update
and try this command again
php spark ci4adminrbac:install

**Comment by bangil0** [comment]
i got this error

An uncaught Exception was encountered

Type:        mysqli_sql_exception
Message:     Table 'ci4_adminlte.tbl_modules' doesn't exist
Filename:    /var/www/html/ci4/ci4adminlte/vendor/codeigniter4/codeigniter4/system/Database/MySQLi/Connection.php
Line Number: 329

**Comment by horasjey** [comment]
eror yang sama

**Comment by skuadron45** [comment]
i am sorry, a didn't update this package for a long time, may be i will check it later and update this package if possible

**Comment by skuadron45** [comment]
already update the package for latest ci and using mariadb 10.11.x
