### ISSUE TITLE
php spark ci4adminrbac:install

### ISSUE THREAD

**Issue by novalhabibi** [skuadron45/ci4adminlte#2]
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to CodeIgniter\CLI\Console::__construct() must be an instance of CodeIgniter\CodeIgniter, int given, called in /var/www/html/ci4adminlte/spark on line 47 and defined in /var/www/html/ci4adminlte/vendor/codeigniter4/codeigniter4/system/CLI/Console.php:29
Stack trace:
#0 /var/www/html/ci4adminlte/spark(47): CodeIgniter\CLI\Console->__construct()
#1 {main}
  thrown in /var/www/html/ci4adminlte/vendor/codeigniter4/codeigniter4/system/CLI/Console.php on line 29

**Comment by skuadron45** [comment]
already update the package for latest ci and using mariadb 10.11.x

**Comment by novalhabibi** [comment]
Cara atau contoh pekamaian Modulnya gimana gan?
Kurang dokumentasi nih :pray:
